function [RJ_MCMC_THBI_state] = emptystate_MCMC()
% [RJ_MCMC_THBI_state]=EMPTYSTATE_MCMC()
%
% Preallocate all of the Markov chain variables used to compute proposed
% models and all of the ensemble variables used for posterior statistics.
% 
% OUTPUT:
%
% RJ_MCMC_THBI_state    A structure containing all of the Markov chain
%                       variables.
%
% Last modified by kengourley-at-arizona.edu, 8-13-2024

    RJ_MCMC_THBI_state = struct(...
    'LogPosterior',                 [],...
    'LogLikelihood',                [],...
    'LogPrior',                     [],...
    'Log_Alpha_Ratio',              [],...
    'Misfit',                       [],...
    'Residual',                     [],...
    'Zmax',                         [],...
    'Zmin',                         [],...
    'Proposed_Layers',              [],...
    'Current_Layers',               [],...
    'NProposed_Layers',             [],...
    'NCurrent_Layers',              [],...
    'Fixed_Visc_depth',             [],...
    'Max_Visc_value',               [],...
    'Min_Visc_value',               [],...
    'Proposed_Viscosity',           [],...
    'Viscosity_Increase',           [],...
    'Relative_Viscosity',           [],...
    'Relative_Viscosity_depth',     [],...
    'Current_Viscosity',            [],...
    'Maximum_Degree',               [],...
    'Noden',                        [],...
    'Tomography',                   [],...
    'Scaling',                      [],...
    'Step',                         [],...
    'Region',                       [],...
    'Fixed_Visc_Contrast',          [],...
    'Observed_Geoid',              	[],...
    'Kernel_Geoid',               	[],...
    'Proposed_Geoid',             	[],...
    'Iteration',                    [],...
    'Accpetance',                   [],...
    'Rejection',                    [],...
    'ABirth_count',                 [],...
    'RBirth_count',                 [],...
    'ADeath_count',                 [],...
    'RDeath_count',                 [],...
    'AValue_count',                 [],...
    'RValue_count',                 [],...
    'AMove_count',                  [],...
    'RMove_count',                  [],...
    'ANoise_count',                 [],...
    'RNoise_count',                 [],...
    'Uncertainty_Current',          [],...
    'Uncertainty_Proposed',         [],...
    'NoiseType',                    [],...
    'SigmaInit',                    [],...
    'SigmaCurrent',                 [],...    
    'HyperSigma_I',                 [],...
    'HyperSigma_II',                [],...
    'SigmaProposed',                [],...
    'RMS_Error',                    [],...
    'Prefactor',		    []);
end
